test_findif_cr_closed_singlet.test_findif_HF ... ok
test_findif_cr_closed_singlet.test_findif_LDA ... ERROR

======================================================================
ERROR: test_findif_cr_closed_singlet.test_findif_LDA
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/fdrsp/test_findif_cr_closed_singlet.py", line 41, in test_findif_LDA
    cr = RspCalc('XXQUADRU', 'YYQUADRU', 'ZZQUADRU', 'YDIPLEN', wf=wf, dal=dal, mol=inp["h2o"]).exe()
  File "/tmp/fdrsp/findif.py", line 200, in exe
    raise ValueError
ValueError: 
-------------------- >> begin captured stdout << ---------------------
Dalton called OK
Dalton called OK
Dalton called OK

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 2 tests in 31.149s

FAILED (errors=1)
